# NKregion

# MySQL connection (required)
use-mysql: false
table-prefix: NKregion_
host: localhost
port: 3306
dbName: minecraft_dev
user: root
password: 


# Options

# The same name gave to Bungee config
server-name: 'world'